spring:
  application:
    name: vmall_shipment_service
  datasource:
    url: jdbc:mysql://localhost:3307/vmall_shipment
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    server-url: http://localhost:8761/eureka/